#ifndef DATA_STRINGS_H
#define DATA_STRINGS_H

#include "bn_vector.h"
#include "bn_string_view.h"

class data_strings
{
    public:
        bn::vector<bn::string_view, 21> races = bn::vector<bn::string_view, 21>();
        bn::vector<bn::string_view, 18> classes = bn::vector<bn::string_view, 18>();
        bn::vector<bn::string_view, 8> stats = bn::vector<bn::string_view, 8>();
        bn::vector<bn::string_view, 45> spells = bn::vector<bn::string_view, 45>();
        bn::vector<bn::string_view, 11> equipment_titles = bn::vector<bn::string_view, 11>();
        bn::vector<bn::string_view, 38> equipment_weapon = bn::vector<bn::string_view, 38>();
        bn::vector<short, 38> equipment_weapon_val = bn::vector<short, 38>();
        bn::vector<bn::string_view, 38> equipment_shield = bn::vector<bn::string_view, 16>();
        bn::vector<short, 38> equipment_shield_val = bn::vector<short, 16>();
        bn::vector<bn::string_view, 38> equipment_armour = bn::vector<bn::string_view, 20>();
        bn::vector<short, 38> equipment_armour_val = bn::vector<short, 20>();
        bn::vector<bn::string_view, 38> equipment_off = bn::vector<bn::string_view, 11>();
        bn::vector<short, 38> equipment_off_val = bn::vector<short, 11>();
        bn::vector<bn::string_view, 38> equipment_def = bn::vector<bn::string_view, 9>();
        bn::vector<short, 38> equipment_def_val = bn::vector<short, 9>();
        bn::vector<bn::string_view, 38> equipment_off_bad = bn::vector<bn::string_view, 9>();
        bn::vector<short, 38> equipment_off_bad_val = bn::vector<short, 9>();
        bn::vector<bn::string_view, 38> equipment_def_bad = bn::vector<bn::string_view, 14>();
        bn::vector<short, 38> equipment_def_bad_val = bn::vector<short, 14>();
        bn::vector<bn::string_view, 37> item_specials = bn::vector<bn::string_view, 37>();
        bn::vector<bn::string_view, 33> item_modifiers = bn::vector<bn::string_view, 33>();
        bn::vector<bn::string_view, 51> item_of = bn::vector<bn::string_view, 51>();
        bn::vector<bn::string_view, 42> items_boring = bn::vector<bn::string_view, 42>();
        bn::vector<bn::string_view, 231> items_monster = bn::vector<bn::string_view, 231>();
        bn::vector<unsigned char, 231> items_monster_val = bn::vector<unsigned char, 231>();
        bn::vector<bn::string_view, 9> titles = bn::vector<bn::string_view, 9>();

        data_strings()
        {
            races.push_back("Half Orc");
            races.push_back("Half Man");
            races.push_back("Half Halfling");
            races.push_back("Double Hobbit");
            races.push_back("Gobhobbit");
            races.push_back("Low Elf");
            races.push_back("Dung Elf");
            races.push_back("Talking Pony");
            races.push_back("Gyrognome");
            races.push_back("Lesser Dwarf");
            races.push_back("Crested Dwarf");
            races.push_back("Eel Man");
            races.push_back("Panda Man");
            races.push_back("Trans-Kobold");
            races.push_back("Ench'ed M'cycle");
            races.push_back("Will o' the Wisp");
            races.push_back("Battle-Finch");
            races.push_back("Double Wookiee");
            races.push_back("Skraeling");
            races.push_back("Demicanadian");
            races.push_back("Land Squid");

            classes.push_back("Ur-Paladin");
            classes.push_back("Voodoo Princess");
            classes.push_back("Robot Monk");
            classes.push_back("Mu-Fu Monk");
            classes.push_back("Mage Illusioner");
            classes.push_back("Shiv-Knight");
            classes.push_back("Inner Mason");
            classes.push_back("Fighter/Organist");
            classes.push_back("Puma Burgular");
            classes.push_back("Runeloremaster");
            classes.push_back("Hunter Strangler");
            classes.push_back("Battle-Felon");
            classes.push_back("Tickle-Mimic");
            classes.push_back("Slow Poisoner");
            classes.push_back("Bastard Lunatic");
            classes.push_back("Jungle Clown");
            classes.push_back("Birdrider");
            classes.push_back("Vermineer");

            stats.push_back("STR");
            stats.push_back("DEX");
            stats.push_back("CON");
            stats.push_back("INT");
            stats.push_back("WIS");
            stats.push_back("CHA");
            stats.push_back("HP Max");
            stats.push_back("MP Max");

            spells.push_back("Slime Finger");
            spells.push_back("Rabbit Punch");
            spells.push_back("Hastiness");
            spells.push_back("Good Move");
            spells.push_back("Sadness");
            spells.push_back("Seasick");
            spells.push_back("Shoelaces");
            spells.push_back("Inoculate");
            spells.push_back("Cone of/    Annoyance");
            spells.push_back("Magnetic Orb");
            spells.push_back("Invisible/    Hands");
            spells.push_back("Revolting/    Cloud");
            spells.push_back("Aqueous/    Humor");
            spells.push_back("Spectral/    Miasma");
            spells.push_back("Clever Fellow");
            spells.push_back("Lockjaw");
            spells.push_back("History/    Lesson");
            spells.push_back("Hydrophobia");
            spells.push_back("Big Sister");
            spells.push_back("Cone of Paste");
            spells.push_back("Mulligan");
            spells.push_back("Nestor's/    Bright Idea");
            spells.push_back("Holy Batpole");
            spells.push_back("Tumor/    (Benign)");
            spells.push_back("Braingate");
            spells.push_back("Nonplus");
            spells.push_back("Animate/    Nightstand");
            spells.push_back("Eye of the/    Troglodyte");
            spells.push_back("Curse Name");
            spells.push_back("Dropsy");
            spells.push_back("Vitreous/    Humor");
            spells.push_back("Roger's Grand/    Illusion");
            spells.push_back("Covet");
            spells.push_back("Astral Miasma");
            spells.push_back("Spectral/    Oyster");
            spells.push_back("Acrid Hands");
            spells.push_back("Angioplasty");
            spells.push_back("Grognor's Big/    Day Off");
            spells.push_back("Tumor/    (Malignant)");
            spells.push_back("Animate Tunic");
            spells.push_back("Ursine Armor");
            spells.push_back("Holy Roller");
            spells.push_back("Tonsillectomy");
            spells.push_back("Curse Family");
            spells.push_back("Infinite/    Confusion");

            equipment_titles.push_back("Weapon");
            equipment_titles.push_back("Shield");
            equipment_titles.push_back("Helm");
            equipment_titles.push_back("Hauberk");
            equipment_titles.push_back("Brassairts");
            equipment_titles.push_back("Vambraces");
            equipment_titles.push_back("Gauntlets");
            equipment_titles.push_back("Gambeson");
            equipment_titles.push_back("Cuisses");
            equipment_titles.push_back("Greaves");
            equipment_titles.push_back("Sollerets");

            equipment_weapon.push_back("Stick");
            equipment_weapon.push_back("Broken Bottle");
            equipment_weapon.push_back("Shiv");
            equipment_weapon.push_back("Sprig");
            equipment_weapon.push_back("Oxgoad");
            equipment_weapon.push_back("Eelspear");
            equipment_weapon.push_back("Bowie Knife");
            equipment_weapon.push_back("Claw Hammer");
            equipment_weapon.push_back("Handpeen");
            equipment_weapon.push_back("Andiron");
            equipment_weapon.push_back("Hatchet");
            equipment_weapon.push_back("Tomahawk");
            equipment_weapon.push_back("Hackbarm");
            equipment_weapon.push_back("Crowbar");
            equipment_weapon.push_back("Mace");
            equipment_weapon.push_back("Battleadze");
            equipment_weapon.push_back("Leafmace");
            equipment_weapon.push_back("Shortsword");
            equipment_weapon.push_back("Longiron");
            equipment_weapon.push_back("Poachard");
            equipment_weapon.push_back("Baselard");
            equipment_weapon.push_back("Whinyard");
            equipment_weapon.push_back("Blunderbuss");
            equipment_weapon.push_back("Longsword");
            equipment_weapon.push_back("Crankbow");
            equipment_weapon.push_back("Blibo");
            equipment_weapon.push_back("Broadsword");
            equipment_weapon.push_back("Kreen");
            equipment_weapon.push_back("Morning Star");
            equipment_weapon.push_back("Pole-adze");
            equipment_weapon.push_back("Spontoon");
            equipment_weapon.push_back("Bastard Sword");
            equipment_weapon.push_back("Peen-arm");
            equipment_weapon.push_back("Culverin");
            equipment_weapon.push_back("Lance");
            equipment_weapon.push_back("Halberd");
            equipment_weapon.push_back("Poleax");
            equipment_weapon.push_back("Bandyclef");

            equipment_weapon_val.push_back(0);
            equipment_weapon_val.push_back(1);
            equipment_weapon_val.push_back(1);
            equipment_weapon_val.push_back(1);
            equipment_weapon_val.push_back(1);
            equipment_weapon_val.push_back(2);
            equipment_weapon_val.push_back(2);
            equipment_weapon_val.push_back(2);
            equipment_weapon_val.push_back(2);
            equipment_weapon_val.push_back(3);
            equipment_weapon_val.push_back(3);
            equipment_weapon_val.push_back(3);
            equipment_weapon_val.push_back(3);
            equipment_weapon_val.push_back(4);
            equipment_weapon_val.push_back(4);
            equipment_weapon_val.push_back(4);
            equipment_weapon_val.push_back(5);
            equipment_weapon_val.push_back(5);
            equipment_weapon_val.push_back(5);
            equipment_weapon_val.push_back(5);
            equipment_weapon_val.push_back(5);
            equipment_weapon_val.push_back(6);
            equipment_weapon_val.push_back(6);
            equipment_weapon_val.push_back(6);
            equipment_weapon_val.push_back(6);
            equipment_weapon_val.push_back(7);
            equipment_weapon_val.push_back(7);
            equipment_weapon_val.push_back(7);
            equipment_weapon_val.push_back(8);
            equipment_weapon_val.push_back(8);
            equipment_weapon_val.push_back(8);
            equipment_weapon_val.push_back(9);
            equipment_weapon_val.push_back(9);
            equipment_weapon_val.push_back(10);
            equipment_weapon_val.push_back(10);
            equipment_weapon_val.push_back(11);
            equipment_weapon_val.push_back(12);
            equipment_weapon_val.push_back(15);

            equipment_shield.push_back("Parasol");
            equipment_shield.push_back("Pie Plate");
            equipment_shield.push_back("Garbage Can Lid");
            equipment_shield.push_back("Buckler");
            equipment_shield.push_back("Plexiglass");
            equipment_shield.push_back("Fender");
            equipment_shield.push_back("Round Shield");
            equipment_shield.push_back("Carapace");
            equipment_shield.push_back("Scutum");
            equipment_shield.push_back("Propugner");
            equipment_shield.push_back("Kite Shield");
            equipment_shield.push_back("Pavise");
            equipment_shield.push_back("Tower Shield");
            equipment_shield.push_back("Baroque Shield");
            equipment_shield.push_back("Aegis");
            equipment_shield.push_back("Magnetic Field");

            equipment_shield_val.push_back(0);
            equipment_shield_val.push_back(1);
            equipment_shield_val.push_back(2);
            equipment_shield_val.push_back(3);
            equipment_shield_val.push_back(4);
            equipment_shield_val.push_back(4);
            equipment_shield_val.push_back(5);
            equipment_shield_val.push_back(5);
            equipment_shield_val.push_back(6);
            equipment_shield_val.push_back(6);
            equipment_shield_val.push_back(7);
            equipment_shield_val.push_back(8);
            equipment_shield_val.push_back(9);
            equipment_shield_val.push_back(11);
            equipment_shield_val.push_back(12);
            equipment_shield_val.push_back(18);

            equipment_armour.push_back("Lace");
            equipment_armour.push_back("Macrame");
            equipment_armour.push_back("Burlap");
            equipment_armour.push_back("Canvas");
            equipment_armour.push_back("Flannel");
            equipment_armour.push_back("Chamois");
            equipment_armour.push_back("Pleathers");
            equipment_armour.push_back("Leathers");
            equipment_armour.push_back("Bearskin");
            equipment_armour.push_back("Ringmail");
            equipment_armour.push_back("Scale Mail");
            equipment_armour.push_back("Chainmail");
            equipment_armour.push_back("Splint Mail");
            equipment_armour.push_back("Platemail");
            equipment_armour.push_back("ABS");
            equipment_armour.push_back("Kevlar");
            equipment_armour.push_back("Titanium");
            equipment_armour.push_back("Mithril Mail");
            equipment_armour.push_back("Diamond Mail");
            equipment_armour.push_back("Plasma");

            equipment_armour_val.push_back(1);
            equipment_armour_val.push_back(2);
            equipment_armour_val.push_back(3);
            equipment_armour_val.push_back(4);
            equipment_armour_val.push_back(5);
            equipment_armour_val.push_back(6);
            equipment_armour_val.push_back(7);
            equipment_armour_val.push_back(8);
            equipment_armour_val.push_back(9);
            equipment_armour_val.push_back(10);
            equipment_armour_val.push_back(12);
            equipment_armour_val.push_back(14);
            equipment_armour_val.push_back(15);
            equipment_armour_val.push_back(16);
            equipment_armour_val.push_back(17);
            equipment_armour_val.push_back(18);
            equipment_armour_val.push_back(19);
            equipment_armour_val.push_back(20);
            equipment_armour_val.push_back(25);
            equipment_armour_val.push_back(30);

            equipment_off.push_back("Polished");
            equipment_off.push_back("Serrated");
            equipment_off.push_back("Heavy");
            equipment_off.push_back("Pronged");
            equipment_off.push_back("Steely");
            equipment_off.push_back("Vicious");
            equipment_off.push_back("Venomed");
            equipment_off.push_back("Stabbity");
            equipment_off.push_back("Dancing");
            equipment_off.push_back("Invisible");
            equipment_off.push_back("Vorpal");

            equipment_off_val.push_back(1);
            equipment_off_val.push_back(1);
            equipment_off_val.push_back(1);
            equipment_off_val.push_back(2);
            equipment_off_val.push_back(2);
            equipment_off_val.push_back(3);
            equipment_off_val.push_back(4);
            equipment_off_val.push_back(4);
            equipment_off_val.push_back(5);
            equipment_off_val.push_back(6);
            equipment_off_val.push_back(7);

            equipment_def.push_back("Studded");
            equipment_def.push_back("Banded");
            equipment_def.push_back("Gilded");
            equipment_def.push_back("Festooned");
            equipment_def.push_back("Holy");
            equipment_def.push_back("Cambric");
            equipment_def.push_back("Fine");
            equipment_def.push_back("Impressive");
            equipment_def.push_back("Custom");

            equipment_def_val.push_back(1);
            equipment_def_val.push_back(2);
            equipment_def_val.push_back(2);
            equipment_def_val.push_back(3);
            equipment_def_val.push_back(4);
            equipment_def_val.push_back(1);
            equipment_def_val.push_back(4);
            equipment_def_val.push_back(5);
            equipment_def_val.push_back(3);

            equipment_off_bad.push_back("Dull");
            equipment_off_bad.push_back("Tarnished");
            equipment_off_bad.push_back("Rusty");
            equipment_off_bad.push_back("Padded");
            equipment_off_bad.push_back("Bent");
            equipment_off_bad.push_back("Mini");
            equipment_off_bad.push_back("Rubber");
            equipment_off_bad.push_back("Nerf");
            equipment_off_bad.push_back("Unbalanced");

            equipment_off_bad_val.push_back(-2);
            equipment_off_bad_val.push_back(-1);
            equipment_off_bad_val.push_back(-3);
            equipment_off_bad_val.push_back(-5);
            equipment_off_bad_val.push_back(-4);
            equipment_off_bad_val.push_back(-4);
            equipment_off_bad_val.push_back(-6);
            equipment_off_bad_val.push_back(-7);
            equipment_off_bad_val.push_back(-2);

            equipment_def_bad.push_back("Holey");
            equipment_def_bad.push_back("Patched");
            equipment_def_bad.push_back("Threadbare");
            equipment_def_bad.push_back("Faded");
            equipment_def_bad.push_back("Rusty");
            equipment_def_bad.push_back("Motheaten");
            equipment_def_bad.push_back("Mildewed");
            equipment_def_bad.push_back("Torn");
            equipment_def_bad.push_back("Dented");
            equipment_def_bad.push_back("Cursed");
            equipment_def_bad.push_back("Plastic");
            equipment_def_bad.push_back("Cracked");
            equipment_def_bad.push_back("Warped");
            equipment_def_bad.push_back("Corroded");

            equipment_def_bad_val.push_back(-1);
            equipment_def_bad_val.push_back(-1);
            equipment_def_bad_val.push_back(-2);
            equipment_def_bad_val.push_back(-1);
            equipment_def_bad_val.push_back(-3);
            equipment_def_bad_val.push_back(-3);
            equipment_def_bad_val.push_back(-2);
            equipment_def_bad_val.push_back(-3);
            equipment_def_bad_val.push_back(-3);
            equipment_def_bad_val.push_back(-5);
            equipment_def_bad_val.push_back(-4);
            equipment_def_bad_val.push_back(-4);
            equipment_def_bad_val.push_back(-3);
            equipment_def_bad_val.push_back(-3);

            item_specials.push_back("Diadem");
            item_specials.push_back("Festoon");
            item_specials.push_back("Gemstone");
            item_specials.push_back("Phial");
            item_specials.push_back("Tiara");
            item_specials.push_back("Scabbard");
            item_specials.push_back("Arrow");
            item_specials.push_back("Lens");
            item_specials.push_back("Lamp");
            item_specials.push_back("Hymnal");
            item_specials.push_back("Fleece");
            item_specials.push_back("Laurel");
            item_specials.push_back("Brooch");
            item_specials.push_back("Gimlet");
            item_specials.push_back("Cobble");
            item_specials.push_back("Albatross");
            item_specials.push_back("Brazier");
            item_specials.push_back("Bandolier");
            item_specials.push_back("Tome");
            item_specials.push_back("Garnet");
            item_specials.push_back("Amethyst");
            item_specials.push_back("Candelabra");
            item_specials.push_back("Corset");
            item_specials.push_back("Sphere");
            item_specials.push_back("Sceptre");
            item_specials.push_back("Ankh");
            item_specials.push_back("Talisman");
            item_specials.push_back("Orb");
            item_specials.push_back("Gammel");
            item_specials.push_back("Ornament");
            item_specials.push_back("Brocade");
            item_specials.push_back("Galoon");
            item_specials.push_back("Bijou");
            item_specials.push_back("Spangle");
            item_specials.push_back("Gimcrack");
            item_specials.push_back("Hood");
            item_specials.push_back("Vulpeculum");

            item_modifiers.push_back("Golden");
            item_modifiers.push_back("Gilded");
            item_modifiers.push_back("Spectral");
            item_modifiers.push_back("Astral");
            item_modifiers.push_back("Garlanded");
            item_modifiers.push_back("Precious");
            item_modifiers.push_back("Crafted");
            item_modifiers.push_back("Dual");
            item_modifiers.push_back("Filigreed");
            item_modifiers.push_back("Cruciate");
            item_modifiers.push_back("Arcane");
            item_modifiers.push_back("Blessed");
            item_modifiers.push_back("Reverential");
            item_modifiers.push_back("Lucky");
            item_modifiers.push_back("Enchanted");
            item_modifiers.push_back("Gleaming");
            item_modifiers.push_back("Grandiose");
            item_modifiers.push_back("Sacred");
            item_modifiers.push_back("Legendary");
            item_modifiers.push_back("Mythic");
            item_modifiers.push_back("Crystalline");
            item_modifiers.push_back("Austere");
            item_modifiers.push_back("Ostentatious");
            item_modifiers.push_back("One True");
            item_modifiers.push_back("Proverbial");
            item_modifiers.push_back("Fearsome");
            item_modifiers.push_back("Deadly");
            item_modifiers.push_back("Benevolent");
            item_modifiers.push_back("Unearthly");
            item_modifiers.push_back("Magnificent");
            item_modifiers.push_back("Iron");
            item_modifiers.push_back("Ormolu");
            item_modifiers.push_back("Puissant");

            item_of.push_back("Foreboding");
            item_of.push_back("Foreshadowing");
            item_of.push_back("Nervousness");
            item_of.push_back("Happiness");
            item_of.push_back("Torpor");
            item_of.push_back("Danger");
            item_of.push_back("Craft");
            item_of.push_back("Silence");
            item_of.push_back("Invisibility");
            item_of.push_back("Rapidity");
            item_of.push_back("Pleasure");
            item_of.push_back("Practicality");
            item_of.push_back("Hurting");
            item_of.push_back("Joy");
            item_of.push_back("Petulance");
            item_of.push_back("Intrusion");
            item_of.push_back("Chaos");
            item_of.push_back("Suffering");
            item_of.push_back("Extroversion");
            item_of.push_back("Frenzy");
            item_of.push_back("Solitude");
            item_of.push_back("Punctuality");
            item_of.push_back("Efficiency");
            item_of.push_back("Comfort");
            item_of.push_back("Patience");
            item_of.push_back("Internment");
            item_of.push_back("Incarceration");
            item_of.push_back("Misapprehension");
            item_of.push_back("Loyalty");
            item_of.push_back("Envy");
            item_of.push_back("Acrimony");
            item_of.push_back("Worry");
            item_of.push_back("Fear");
            item_of.push_back("Awe");
            item_of.push_back("Guile");
            item_of.push_back("Prurience");
            item_of.push_back("Fortune");
            item_of.push_back("Perspicacity");
            item_of.push_back("Domination");
            item_of.push_back("Submission");
            item_of.push_back("Fealty");
            item_of.push_back("Hunger");
            item_of.push_back("Despair");
            item_of.push_back("Cruelty");
            item_of.push_back("Grob");
            item_of.push_back("Dignard");
            item_of.push_back("Ra");
            item_of.push_back("the Bone");
            item_of.push_back("Diamonique");
            item_of.push_back("Electrum");
            item_of.push_back("Hydragyrum");

            items_boring.push_back("nail");
            items_boring.push_back("lunchpail");
            items_boring.push_back("sock");
            items_boring.push_back("I.O.U.");
            items_boring.push_back("cookie");
            items_boring.push_back("pint");
            items_boring.push_back("toothpick");
            items_boring.push_back("writ");
            items_boring.push_back("newspaper");
            items_boring.push_back("letter");
            items_boring.push_back("plank");
            items_boring.push_back("hat");
            items_boring.push_back("egg");
            items_boring.push_back("coin");
            items_boring.push_back("needle");
            items_boring.push_back("bucket");
            items_boring.push_back("ladder");
            items_boring.push_back("chicken");
            items_boring.push_back("twig");
            items_boring.push_back("dirtclod");
            items_boring.push_back("counterpane");
            items_boring.push_back("vest");
            items_boring.push_back("teratoma");
            items_boring.push_back("bunny");
            items_boring.push_back("rock");
            items_boring.push_back("pole");
            items_boring.push_back("carrot");
            items_boring.push_back("canoe");
            items_boring.push_back("inkwell");
            items_boring.push_back("hoe");
            items_boring.push_back("bandage");
            items_boring.push_back("trowel");
            items_boring.push_back("towel");
            items_boring.push_back("planter box");
            items_boring.push_back("anvil");
            items_boring.push_back("axle");
            items_boring.push_back("tuppence");
            items_boring.push_back("casket");
            items_boring.push_back("nosegay");
            items_boring.push_back("trinket");
            items_boring.push_back("credenza");
            items_boring.push_back("writ");

            items_monster.push_back("Anhkheg|chitin");
            items_monster.push_back("Ant|antenna");
            items_monster.push_back("Ape|ass");
            items_monster.push_back("Baluchitherium|ear");
            items_monster.push_back("Beholder|eyestalk");
            items_monster.push_back("Black Pudding|saliva");
            items_monster.push_back("Blink Dog|eyelid");
            items_monster.push_back("Cub Scout|neckerchief");
            items_monster.push_back("Girl Scout|cookie");
            items_monster.push_back("Boy Scout|merit badge");
            items_monster.push_back("Eagle Scout|merit badge");
            items_monster.push_back("Bugbear|skin");
            items_monster.push_back("Bugboar|tusk");
            items_monster.push_back("Boogie|slime");
            items_monster.push_back("Camel|hump");
            items_monster.push_back("Carrion Crawler|egg");
            items_monster.push_back("Catoblepas|neck");
            items_monster.push_back("Centaur|rib");
            items_monster.push_back("Centipede|leg");
            items_monster.push_back("Cockatrice|wattle");
            items_monster.push_back("Couatl|wing");
            items_monster.push_back("Crayfish|antenna");
            items_monster.push_back("Demogorgon|tentacle");
            items_monster.push_back("Jubilex|gel");
            items_monster.push_back("Manes|tooth");
            items_monster.push_back("Orcus|wand");
            items_monster.push_back("Succubus|bra");
            items_monster.push_back("Vrock|neck");
            items_monster.push_back("Hezrou|leg");
            items_monster.push_back("Glabrezu|collar");
            items_monster.push_back("Nalfeshnee|tusk");
            items_monster.push_back("Marilith|arm");
            items_monster.push_back("Balor|whip");
            items_monster.push_back("Yeenoghu|flail");
            items_monster.push_back("Asmodeus|leathers");
            items_monster.push_back("Baalzebul|pants");
            items_monster.push_back("Barbed Devil|flame");
            items_monster.push_back("Bone Devil|hook");
            items_monster.push_back("Dispater|matches");
            items_monster.push_back("Erinyes|thong");
            items_monster.push_back("Geryon|cornucopia");
            items_monster.push_back("Malebranche|fork");
            items_monster.push_back("Ice Devil|snow");
            items_monster.push_back("Lemure|blob");
            items_monster.push_back("Pit Fiend|seed");
            items_monster.push_back("Ankylosaurus|tail");
            items_monster.push_back("Brontosaurus|brain");
            items_monster.push_back("Diplodocus|fin");
            items_monster.push_back("Elasmosaurus|neck");
            items_monster.push_back("Gorgosaurus|arm");
            items_monster.push_back("Iguanadon|thumb");
            items_monster.push_back("Megalosaurus|jaw");
            items_monster.push_back("Monoclonius|horn");
            items_monster.push_back("Pentasaurus|head");
            items_monster.push_back("Stegosaurus|plate");
            items_monster.push_back("Triceratops|horn");
            items_monster.push_back("Tyrannosaurus Rex|forearm");
            items_monster.push_back("Djinn|lamp");
            items_monster.push_back("Doppelganger|face");
            items_monster.push_back("Black Dragon|*");
            items_monster.push_back("Plaid Dragon|sporrin");
            items_monster.push_back("Blue Dragon|*");
            items_monster.push_back("Beige Dragon|*");
            items_monster.push_back("Brass Dragon|pole");
            items_monster.push_back("Tin Dragon|*");
            items_monster.push_back("Bronze Dragon|medal");
            items_monster.push_back("Chromatic Dragon|scale");
            items_monster.push_back("Copper Dragon|loafer");
            items_monster.push_back("Gold Dragon|filling");
            items_monster.push_back("Green Dragon|*");
            items_monster.push_back("Platinum Dragon|*");
            items_monster.push_back("Red Dragon|cocktail");
            items_monster.push_back("Silver Dragon|*");
            items_monster.push_back("White Dragon|tooth");
            items_monster.push_back("Dragon Turtle|shell");
            items_monster.push_back("Dryad|acorn");
            items_monster.push_back("Dwarf|drawers");
            items_monster.push_back("Eel|sashimi");
            items_monster.push_back("Efreet|cinder");
            items_monster.push_back("Sand Elemental|glass");
            items_monster.push_back("Bacon Elemental|bit");
            items_monster.push_back("Porn Elemental|lube");
            items_monster.push_back("Cheese Elemental|curd");
            items_monster.push_back("Hair Elemental|follicle");
            items_monster.push_back("Swamp Elf|lilypad");
            items_monster.push_back("Brown Elf|tusk");
            items_monster.push_back("Sea Elf|jerkin");
            items_monster.push_back("Ettin|fur");
            items_monster.push_back("Frog|leg");
            items_monster.push_back("Violet Fungi|spore");
            items_monster.push_back("Gargoyle|gravel");
            items_monster.push_back("Gelatinous Cube|jam");
            items_monster.push_back("Ghast|vomit");
            items_monster.push_back("Ghost|*");
            items_monster.push_back("Ghoul|muscle");
            items_monster.push_back("Humidity Giant|drops");
            items_monster.push_back("Beef Giant|steak");
            items_monster.push_back("Quartz Giant|crystal");
            items_monster.push_back("Porcelain Giant|fixture");
            items_monster.push_back("Rice Giant|grain");
            items_monster.push_back("Cloud Giant|condensation");
            items_monster.push_back("Fire Giant|cigarettes");
            items_monster.push_back("Frost Giant|snowman");
            items_monster.push_back("Hill Giant|corpse");
            items_monster.push_back("Stone Giant|hatchling");
            items_monster.push_back("Storm Giant|barometer");
            items_monster.push_back("Mini Giant|pompadour");
            items_monster.push_back("Gnoll|collar");
            items_monster.push_back("Gnome|hat");
            items_monster.push_back("Goblin|ear");
            items_monster.push_back("Grid Bug|carapace");
            items_monster.push_back("Jellyrock|seedling");
            items_monster.push_back("Beer Golem|foam");
            items_monster.push_back("Oxygen Golem|platelet");
            items_monster.push_back("Cardboard Golem|recycling");
            items_monster.push_back("Rubber Golem|ball");
            items_monster.push_back("Leather Golem|fob");
            items_monster.push_back("Gorgon|testicle");
            items_monster.push_back("Gray Ooze|gravy");
            items_monster.push_back("Green Slime|sample");
            items_monster.push_back("Griffon|nest");
            items_monster.push_back("Banshee|larynx");
            items_monster.push_back("Harpy|mascara");
            items_monster.push_back("Hell Hound|tongue");
            items_monster.push_back("Hippocampus|mane");
            items_monster.push_back("Hippogriff|egg");
            items_monster.push_back("Hobgoblin|patella");
            items_monster.push_back("Homunculus|fluid");
            items_monster.push_back("Hydra|gyrum");
            items_monster.push_back("Imp|tail");
            items_monster.push_back("Invisible Stalker|*");
            items_monster.push_back("Iron Peasant|chaff");
            items_monster.push_back("Jumpskin|shin");
            items_monster.push_back("Kobold|penis");
            items_monster.push_back("Leprechaun|wallet");
            items_monster.push_back("Leucrotta|hoof");
            items_monster.push_back("Lich|crown");
            items_monster.push_back("Lizard Man|tail");
            items_monster.push_back("Lurker|sac");
            items_monster.push_back("Manticore|spike");
            items_monster.push_back("Mastodon|tusk");
            items_monster.push_back("Medusa|eye");
            items_monster.push_back("Multicell|dendrite");
            items_monster.push_back("Pirate|booty");
            items_monster.push_back("Berserker|shirt");
            items_monster.push_back("Caveman|club");
            items_monster.push_back("Dervish|robe");
            items_monster.push_back("Merman|trident");
            items_monster.push_back("Mermaid|gills");
            items_monster.push_back("Mimic|hinge");
            items_monster.push_back("Mind Flayer|tentacle");
            items_monster.push_back("Minotaur|map");
            items_monster.push_back("Yellow Mold|spore");
            items_monster.push_back("Morkoth|teeth");
            items_monster.push_back("Mummy|gauze");
            items_monster.push_back("Naga|rattle");
            items_monster.push_back("Nebbish|belly");
            items_monster.push_back("Neo-Otyugh|organ ");
            items_monster.push_back("Nixie|webbing");
            items_monster.push_back("Nymph|hanky");
            items_monster.push_back("Ochre Jelly|nucleus");
            items_monster.push_back("Octopus|beak");
            items_monster.push_back("Ogre|talon");
            items_monster.push_back("Ogre Mage|apparel");
            items_monster.push_back("Orc|snout");
            items_monster.push_back("Otyugh|organ");
            items_monster.push_back("Owlbear|feather");
            items_monster.push_back("Pegasus|aileron");
            items_monster.push_back("Peryton|antler");
            items_monster.push_back("Piercer|tip");
            items_monster.push_back("Pixie|dust");
            items_monster.push_back("Man-o-war|tentacle");
            items_monster.push_back("Purple Worm|dung");
            items_monster.push_back("Quasit|tail");
            items_monster.push_back("Rakshasa|pajamas");
            items_monster.push_back("Rat|tail");
            items_monster.push_back("Remorhaz|protrusion");
            items_monster.push_back("Roc|wing");
            items_monster.push_back("Roper|twine");
            items_monster.push_back("Rot Grub|eggsac");
            items_monster.push_back("Rust Monster|shavings");
            items_monster.push_back("Satyr|hoof");
            items_monster.push_back("Sea Hag|wart");
            items_monster.push_back("Silkie|fur");
            items_monster.push_back("Shadow|silhouette");
            items_monster.push_back("Shambling Mound|mulch");
            items_monster.push_back("Shedu|hoof");
            items_monster.push_back("Shrieker|stalk");
            items_monster.push_back("Skeleton|clavicle");
            items_monster.push_back("Spectre|vestige");
            items_monster.push_back("Sphinx|paw");
            items_monster.push_back("Spider|web");
            items_monster.push_back("Sprite|can");
            items_monster.push_back("Stirge|proboscis");
            items_monster.push_back("Stun Bear|tooth");
            items_monster.push_back("Stun Worm|trode");
            items_monster.push_back("Su-monster|tail");
            items_monster.push_back("Sylph|thigh");
            items_monster.push_back("Titan|sandal");
            items_monster.push_back("Trapper|shag");
            items_monster.push_back("Treant|acorn");
            items_monster.push_back("Triton|scale");
            items_monster.push_back("Troglodyte|tail");
            items_monster.push_back("Troll|hide");
            items_monster.push_back("Umber Hulk|claw");
            items_monster.push_back("Unicorn|blood");
            items_monster.push_back("Vampire|pancreas");
            items_monster.push_back("Wight|lung");
            items_monster.push_back("Will-o-the-Wisp|wisp");
            items_monster.push_back("Wraith|finger");
            items_monster.push_back("Wyvern|wing");
            items_monster.push_back("Xorn|jaw");
            items_monster.push_back("Yeti|fur");
            items_monster.push_back("Zombie|forehead");
            items_monster.push_back("Wasp|stinger");
            items_monster.push_back("Rat|tail");
            items_monster.push_back("Bunny|ear");
            items_monster.push_back("Moth|dust");
            items_monster.push_back("Beagle|collar");
            items_monster.push_back("Midge|corpse");
            items_monster.push_back("Ostrich|beak");
            items_monster.push_back("Billy Goat|beard");
            items_monster.push_back("Bat|wing");
            items_monster.push_back("Koala|heart");
            items_monster.push_back("Wolf|paw");
            items_monster.push_back("Whippet|collar");
            items_monster.push_back("Uruk|boot");
            items_monster.push_back("Poroid|node");
            items_monster.push_back("Moakum|frenum");
            items_monster.push_back("Fly|*");
            items_monster.push_back("Hogbird|curl");

            items_monster_val.push_back(6);
            items_monster_val.push_back(0);
            items_monster_val.push_back(4);
            items_monster_val.push_back(14);
            items_monster_val.push_back(10);
            items_monster_val.push_back(10);
            items_monster_val.push_back(4);
            items_monster_val.push_back(1);
            items_monster_val.push_back(2);
            items_monster_val.push_back(3);
            items_monster_val.push_back(4);
            items_monster_val.push_back(3);
            items_monster_val.push_back(3);
            items_monster_val.push_back(3);
            items_monster_val.push_back(2);
            items_monster_val.push_back(3);
            items_monster_val.push_back(6);
            items_monster_val.push_back(4);
            items_monster_val.push_back(0);
            items_monster_val.push_back(5);
            items_monster_val.push_back(9);
            items_monster_val.push_back(0);
            items_monster_val.push_back(53);
            items_monster_val.push_back(17);
            items_monster_val.push_back(1);
            items_monster_val.push_back(27);
            items_monster_val.push_back(6);
            items_monster_val.push_back(8);
            items_monster_val.push_back(9);
            items_monster_val.push_back(10);
            items_monster_val.push_back(11);
            items_monster_val.push_back(7);
            items_monster_val.push_back(8);
            items_monster_val.push_back(25);
            items_monster_val.push_back(52);
            items_monster_val.push_back(43);
            items_monster_val.push_back(8);
            items_monster_val.push_back(9);
            items_monster_val.push_back(30);
            items_monster_val.push_back(6);
            items_monster_val.push_back(30);
            items_monster_val.push_back(5);
            items_monster_val.push_back(11);
            items_monster_val.push_back(3);
            items_monster_val.push_back(13);
            items_monster_val.push_back(9);
            items_monster_val.push_back(30);
            items_monster_val.push_back(24);
            items_monster_val.push_back(15);
            items_monster_val.push_back(13);
            items_monster_val.push_back(6);
            items_monster_val.push_back(12);
            items_monster_val.push_back(8);
            items_monster_val.push_back(12);
            items_monster_val.push_back(18);
            items_monster_val.push_back(16);
            items_monster_val.push_back(18);
            items_monster_val.push_back(7);
            items_monster_val.push_back(4);
            items_monster_val.push_back(7);
            items_monster_val.push_back(7);
            items_monster_val.push_back(9);
            items_monster_val.push_back(9);
            items_monster_val.push_back(7);
            items_monster_val.push_back(8);
            items_monster_val.push_back(9);
            items_monster_val.push_back(16);
            items_monster_val.push_back(8);
            items_monster_val.push_back(8);
            items_monster_val.push_back(8);
            items_monster_val.push_back(21);
            items_monster_val.push_back(10);
            items_monster_val.push_back(10);
            items_monster_val.push_back(6);
            items_monster_val.push_back(13);
            items_monster_val.push_back(2);
            items_monster_val.push_back(1);
            items_monster_val.push_back(2);
            items_monster_val.push_back(10);
            items_monster_val.push_back(8);
            items_monster_val.push_back(10);
            items_monster_val.push_back(12);
            items_monster_val.push_back(14);
            items_monster_val.push_back(16);
            items_monster_val.push_back(1);
            items_monster_val.push_back(1);
            items_monster_val.push_back(1);
            items_monster_val.push_back(10);
            items_monster_val.push_back(0);
            items_monster_val.push_back(3);
            items_monster_val.push_back(4);
            items_monster_val.push_back(4);
            items_monster_val.push_back(4);
            items_monster_val.push_back(10);
            items_monster_val.push_back(2);
            items_monster_val.push_back(12);
            items_monster_val.push_back(11);
            items_monster_val.push_back(10);
            items_monster_val.push_back(9);
            items_monster_val.push_back(8);
            items_monster_val.push_back(12);
            items_monster_val.push_back(11);
            items_monster_val.push_back(10);
            items_monster_val.push_back(8);
            items_monster_val.push_back(9);
            items_monster_val.push_back(15);
            items_monster_val.push_back(4);
            items_monster_val.push_back(2);
            items_monster_val.push_back(1);
            items_monster_val.push_back(1);
            items_monster_val.push_back(1);
            items_monster_val.push_back(9);
            items_monster_val.push_back(15);
            items_monster_val.push_back(17);
            items_monster_val.push_back(14);
            items_monster_val.push_back(16);
            items_monster_val.push_back(15);
            items_monster_val.push_back(8);
            items_monster_val.push_back(3);
            items_monster_val.push_back(2);
            items_monster_val.push_back(7);
            items_monster_val.push_back(7);
            items_monster_val.push_back(3);
            items_monster_val.push_back(5);
            items_monster_val.push_back(4);
            items_monster_val.push_back(3);
            items_monster_val.push_back(1);
            items_monster_val.push_back(2);
            items_monster_val.push_back(8);
            items_monster_val.push_back(2);
            items_monster_val.push_back(8);
            items_monster_val.push_back(3);
            items_monster_val.push_back(3);
            items_monster_val.push_back(1);
            items_monster_val.push_back(1);
            items_monster_val.push_back(6);
            items_monster_val.push_back(11);
            items_monster_val.push_back(2);
            items_monster_val.push_back(10);
            items_monster_val.push_back(6);
            items_monster_val.push_back(12);
            items_monster_val.push_back(6);
            items_monster_val.push_back(2);
            items_monster_val.push_back(1);
            items_monster_val.push_back(1);
            items_monster_val.push_back(2);
            items_monster_val.push_back(1);
            items_monster_val.push_back(1);
            items_monster_val.push_back(1);
            items_monster_val.push_back(9);
            items_monster_val.push_back(8);
            items_monster_val.push_back(6);
            items_monster_val.push_back(1);
            items_monster_val.push_back(7);
            items_monster_val.push_back(6);
            items_monster_val.push_back(9);
            items_monster_val.push_back(1);
            items_monster_val.push_back(11);
            items_monster_val.push_back(1);
            items_monster_val.push_back(3);
            items_monster_val.push_back(6);
            items_monster_val.push_back(2);
            items_monster_val.push_back(4);
            items_monster_val.push_back(5);
            items_monster_val.push_back(1);
            items_monster_val.push_back(7);
            items_monster_val.push_back(5);
            items_monster_val.push_back(4);
            items_monster_val.push_back(4);
            items_monster_val.push_back(3);
            items_monster_val.push_back(1);
            items_monster_val.push_back(3);
            items_monster_val.push_back(15);
            items_monster_val.push_back(3);
            items_monster_val.push_back(7);
            items_monster_val.push_back(0);
            items_monster_val.push_back(11);
            items_monster_val.push_back(18);
            items_monster_val.push_back(11);
            items_monster_val.push_back(1);
            items_monster_val.push_back(5);
            items_monster_val.push_back(5);
            items_monster_val.push_back(3);
            items_monster_val.push_back(3);
            items_monster_val.push_back(3);
            items_monster_val.push_back(10);
            items_monster_val.push_back(9);
            items_monster_val.push_back(3);
            items_monster_val.push_back(1);
            items_monster_val.push_back(7);
            items_monster_val.push_back(10);
            items_monster_val.push_back(0);
            items_monster_val.push_back(1);
            items_monster_val.push_back(1);
            items_monster_val.push_back(5);
            items_monster_val.push_back(2);
            items_monster_val.push_back(5);
            items_monster_val.push_back(3);
            items_monster_val.push_back(20);
            items_monster_val.push_back(12);
            items_monster_val.push_back(10);
            items_monster_val.push_back(3);
            items_monster_val.push_back(2);
            items_monster_val.push_back(6);
            items_monster_val.push_back(8);
            items_monster_val.push_back(4);
            items_monster_val.push_back(8);
            items_monster_val.push_back(4);
            items_monster_val.push_back(9);
            items_monster_val.push_back(5);
            items_monster_val.push_back(7);
            items_monster_val.push_back(7);
            items_monster_val.push_back(4);
            items_monster_val.push_back(2);
            items_monster_val.push_back(0);
            items_monster_val.push_back(1);
            items_monster_val.push_back(0);
            items_monster_val.push_back(0);
            items_monster_val.push_back(0);
            items_monster_val.push_back(0);
            items_monster_val.push_back(1);
            items_monster_val.push_back(1);
            items_monster_val.push_back(1);
            items_monster_val.push_back(2);
            items_monster_val.push_back(2);
            items_monster_val.push_back(2);
            items_monster_val.push_back(2);
            items_monster_val.push_back(4);
            items_monster_val.push_back(8);
            items_monster_val.push_back(0);
            items_monster_val.push_back(3);

            titles.push_back("Mr.");
            titles.push_back("Mrs.");
            titles.push_back("Sir");
            titles.push_back("Sgt.");
            titles.push_back("Ms.");
            titles.push_back("Captain");
            titles.push_back("Chief");
            titles.push_back("Admiral");
            titles.push_back("Saint");
        }

        bool isSpellMultiline(unsigned int i)
        {
            switch (i)
            {
                case 8:
                case 10:
                case 11:
                case 12:
                case 13:
                case 16:
                case 21:
                case 23:
                case 26:
                case 27:
                case 30:
                case 31:
                case 34:
                case 37:
                case 38:
                case 44:
                    return true;
                default:
                    return false;
            }
        }
};

#endif //DATA_STRINGS_H